# OSX build - adjust -I to point to header files for codecs and portaudio
CFLAGS  = -arch x86_64 -Wall -fPIC -O2 -I./include -I/opt/local/include $(OPTS)
LDFLAGS = -arch x86_64 -lpthread /opt/local/lib/libportaudio.a -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework Carbon

EXECUTABLE ?= squeezelite-osx

include Makefile
